const products = [
  {
    id: 1,
    name: "Bolsa Eco Jeans",
    price: "R$ 45,00",
    image: "/produto1.png",
    seller: "Ana Luíza",
    sellerAvatar: "/vendendor-1.png",
  },
  {
    id: 2,
    name: "Camiseta Orgânica",
    price: "R$ 35,00",
    image: "/produto2.png",
    seller: "Lucas Ferreira",
    sellerAvatar: "/vendendor-2.png",
  },
  {
    id: 3,
    name: "Tênis Recycle Step",
    price: "R$ 109,00",
    image: "/produto3.png",
    seller: "Rafael Almeida",
    sellerAvatar: "/vendendor-3.png",
  },
  {
    id: 4,
    name: "Saia de Linho Sustentável",
    price: "R$ 89,00",
    image: "/produto4.png",
    seller: "Pedro Santos",
    sellerAvatar: "/vendendor-4.png",
  },
  {
    id: 5,
    name: "Bolsa Eco Retalhada",
    price: "R$ 89,90",
    image: "/produto5.png",
    seller: "Camila Rocha",
    sellerAvatar: "/vendendor-5.png",
  },
  {
    id: 6,
    name: "Calça Eco Wide Leg",
    price: "R$ 109,90",
    image: "/produto6.png",
    seller: "Juliana Ribeiro",
    sellerAvatar: "/vendendor-6.png",
  },
  {
    id: 7,
    name: "Camiseta EcoFit",
    price: "R$ 60,00",
    image: "/produto7.png",
    seller: "Lara Mendes",
    sellerAvatar: "/vendendor-7.png",
  },
  {
    id: 8,
    name: "Jaqueta Upcycling",
    price: "R$ 108,90",
    image: "/produto8.png",
    seller: "Ricardo Almeida",
    sellerAvatar: "/vendendor-8.png",
  },
]

export default products
