const products = [
  {
    id: 1,
    name: "Bolsa Eco Jeans",
    price: "R$ 45,00",
    image: "/produto1.png",
    seller: "Ana Luíza",
    sellerAvatar: "/vendendor-1.png",
    material: "Jeans",
    tipo: "Acessórios",
    condicao: "Seminova → Usada, mas em ótimo estado",
    tamanho: "M",
  },
  {
    id: 2,
    name: "Camiseta Orgânica",
    price: "R$ 35,00",
    image: "/produto2.png",
    seller: "Lucas Ferreira",
    sellerAvatar: "/vendendor-2.png",
    material: "Algodão",
    tipo: "Camisetas",
    condicao: "Nova → Nunca usada, etiqueta original",
    tamanho: "M",
  },
  {
    id: 3,
    name: "Tênis Recycle Step",
    price: "R$ 109,00",
    image: "/produto3.png",
    seller: "Rafael Almeida",
    sellerAvatar: "/vendendor-3.png",
    material: "Reciclado",
    tipo: "Calçados",
    condicao: "Upcycling → Produto recriado a partir de outra peça",
    tamanho: "42",
  },
  {
    id: 4,
    name: "Saia de Linho Sustentável",
    price: "R$ 89,00",
    image: "/produto4.png",
    seller: "Pedro Santos",
    sellerAvatar: "/vendendor-4.png",
    material: "Linho",
    tipo: "Saias",
    condicao: "Nova → Nunca usada, etiqueta original",
    tamanho: "P",
  },
  {
    id: 5,
    name: "Bolsa Eco Retalhada",
    price: "R$ 89,90",
    image: "/produto5.png",
    seller: "Camila Rocha",
    sellerAvatar: "/vendendor-5.png",
    material: "Upcycling",
    tipo: "Acessórios",
    condicao: "Upcycling → Produto recriado a partir de outra peça",
    tamanho: "G",
  },
  {
    id: 6,
    name: "Calça Eco Wide Leg",
    price: "R$ 109,90",
    image: "/produto6.png",
    seller: "Juliana Ribeiro",
    sellerAvatar: "/vendendor-6.png",
    material: "Poliéster",
    tipo: "Calças",
    condicao: "Seminova → Usada, mas em ótimo estado",
    tamanho: "40",
  },
  {
    id: 7,
    name: "Camiseta EcoFit",
    price: "R$ 60,00",
    image: "/produto7.png",
    seller: "Lara Mendes",
    sellerAvatar: "/vendendor-7.png",
    material: "Malha",
    tipo: "Camisetas",
    condicao: "Reformada → Ajustada, mas preserva a essência original",
    tamanho: "G",
  },
  {
    id: 8,
    name: "Jaqueta Upcycling",
    price: "R$ 108,90",
    image: "/produto8.png",
    seller: "Ricardo Almeida",
    sellerAvatar: "/vendendor-8.png",
    material: "Upcycling",
    tipo: "Casacos",
    condicao: "Upcycling → Produto recriado a partir de outra peça",
    tamanho: "GG",
  },
]

export default products
